export enum SystemErrors {
	USER_NOT_FOUND = "USER_NOT_FOUND",
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	UNAUTHORIZED = "UNAUTHORIZED",
	CREW_NOT_FOUND = "CREW_NOT_FOUND",
	ALREADY_MEMBER = "ALREADY_MEMBER",
	ALREADY_IN_WHITELIST = "ALREADY_IN_WHITELIST",
	USER_NOT_A_MEMBER = "USER_NOT_A_MEMBER",
	USER_NOT_IN_WHITELIST = "USER_NOT_IN_WHITELIST",
}

export type TSystemErrors = keyof typeof SystemErrors;
